/**
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.gls;

import fr.enseeiht.gls.AbstractPDL1RuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class PDL1RuntimeModule extends AbstractPDL1RuntimeModule {
}
