/*
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.gls.ui.tests;

import com.google.inject.Injector;
import fr.enseeiht.gls.simplepdlt2m.ui.internal.Simplepdlt2mActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class PDL1UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Simplepdlt2mActivator.getInstance().getInjector("fr.enseeiht.gls.PDL1");
	}

}
