/*
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.gls.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PDL1AntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/enseeiht/gls/parser/antlr/internal/InternalPDL1.tokens");
	}
}
