/**
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.gls.ui;

import fr.enseeiht.gls.ui.AbstractPDL1UiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class PDL1UiModule extends AbstractPDL1UiModule {
  public PDL1UiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
