/**
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.gls.ide;

import fr.enseeiht.gls.ide.AbstractPDL1IdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class PDL1IdeModule extends AbstractPDL1IdeModule {
}
