/**
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.gls.ui.contentassist;

import fr.enseeiht.gls.ui.contentassist.AbstractPDL1ProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class PDL1ProposalProvider extends AbstractPDL1ProposalProvider {
}
