/**
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.gls.pDL1;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ressource Usage</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.gls.pDL1.Ressource_Usage#getQuantite <em>Quantite</em>}</li>
 *   <li>{@link fr.enseeiht.gls.pDL1.Ressource_Usage#getRessource <em>Ressource</em>}</li>
 * </ul>
 *
 * @see fr.enseeiht.gls.pDL1.PDL1Package#getRessource_Usage()
 * @model
 * @generated
 */
public interface Ressource_Usage extends ProcessElement
{
  /**
   * Returns the value of the '<em><b>Quantite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quantite</em>' attribute.
   * @see #setQuantite(int)
   * @see fr.enseeiht.gls.pDL1.PDL1Package#getRessource_Usage_Quantite()
   * @model
   * @generated
   */
  int getQuantite();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.pDL1.Ressource_Usage#getQuantite <em>Quantite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Quantite</em>' attribute.
   * @see #getQuantite()
   * @generated
   */
  void setQuantite(int value);

  /**
   * Returns the value of the '<em><b>Ressource</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ressource</em>' reference.
   * @see #setRessource(Ressource)
   * @see fr.enseeiht.gls.pDL1.PDL1Package#getRessource_Usage_Ressource()
   * @model
   * @generated
   */
  Ressource getRessource();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.pDL1.Ressource_Usage#getRessource <em>Ressource</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ressource</em>' reference.
   * @see #getRessource()
   * @generated
   */
  void setRessource(Ressource value);

} // Ressource_Usage
