/**
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.gls.pDL1;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Work Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.gls.pDL1.WorkDefinition#getName <em>Name</em>}</li>
 *   <li>{@link fr.enseeiht.gls.pDL1.WorkDefinition#getRessource_Usage <em>Ressource Usage</em>}</li>
 * </ul>
 *
 * @see fr.enseeiht.gls.pDL1.PDL1Package#getWorkDefinition()
 * @model
 * @generated
 */
public interface WorkDefinition extends ProcessElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.enseeiht.gls.pDL1.PDL1Package#getWorkDefinition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.pDL1.WorkDefinition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Ressource Usage</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gls.pDL1.Ressource_Usage}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ressource Usage</em>' containment reference list.
   * @see fr.enseeiht.gls.pDL1.PDL1Package#getWorkDefinition_Ressource_Usage()
   * @model containment="true"
   * @generated
   */
  EList<Ressource_Usage> getRessource_Usage();

} // WorkDefinition
