/**
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.gls.pDL1;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Work Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.gls.pDL1.WorkDefinition#getName <em>Name</em>}</li>
 *   <li>{@link fr.enseeiht.gls.pDL1.WorkDefinition#getRessource <em>Ressource</em>}</li>
 * </ul>
 *
 * @see fr.enseeiht.gls.pDL1.PDL1Package#getWorkDefinition()
 * @model
 * @generated
 */
public interface WorkDefinition extends ProcessElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.enseeiht.gls.pDL1.PDL1Package#getWorkDefinition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.pDL1.WorkDefinition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Ressource</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ressource</em>' reference.
   * @see #setRessource(Ressource)
   * @see fr.enseeiht.gls.pDL1.PDL1Package#getWorkDefinition_Ressource()
   * @model
   * @generated
   */
  Ressource getRessource();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.pDL1.WorkDefinition#getRessource <em>Ressource</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ressource</em>' reference.
   * @see #getRessource()
   * @generated
   */
  void setRessource(Ressource value);

} // WorkDefinition
