/*
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.gls.ui;

import com.google.inject.Injector;
import fr.enseeiht.gls.simplepdlt2m.ui.internal.Simplepdlt2mActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PDL1ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(Simplepdlt2mActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		Simplepdlt2mActivator activator = Simplepdlt2mActivator.getInstance();
		return activator != null ? activator.getInjector(Simplepdlt2mActivator.FR_ENSEEIHT_GLS_PDL1) : null;
	}

}
