/**
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.gls.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class PDL1QuickfixProvider extends DefaultQuickfixProvider {
}
