/**
 * generated by Xtext 2.17.1
 */
package fr.enseeiht.gls.validation;

import fr.enseeiht.gls.validation.AbstractPDL1Validator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class PDL1Validator extends AbstractPDL1Validator {
}
